use_frameworks!

target 'BlockiesSwift_Example' do
  pod 'BlockiesSwift', :path => '../'

  target 'BlockiesSwift_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 1.2.0'
  pod 'Nimble', '~> 7.0.2'
  end
end
